export interface Property {
  id: string;
  code: string;
  name: string;
  location: string;
  neighborhood: string;
  city: string;
  price: number;
  bedrooms: number;
  suites: number;
  area: number;
  parking: number;
  description: string;
  features: string[];
  type: 'apartment' | 'house' | 'development';
  status: 'ready' | 'launch' | 'construction';
  imageUrl: string;
  propertyUrl: string;
}

export const properties: Property[] = [
  {
    id: "1",
    code: "36",
    name: "Apartamento 332m² - 4Q sendo 2 Suítes - Centro",
    location: "Centro, Florianópolis - SC",
    neighborhood: "Centro",
    city: "Florianópolis",
    price: 5990000,
    bedrooms: 4,
    suites: 2,
    area: 332,
    parking: 2,
    description: "Linda vista para o mar! Sala de estar com três ambientes, hidromassagem no apartamento, piscina no rooftop. Uma unidade por andar com planta ampla e linear de frente para o mar. Suíte master com closet.",
    features: ["Vista mar frontal", "332m²", "Hidromassagem", "Piscina rooftop", "Uma unidade por andar", "Closet", "3 ambientes"],
    type: "apartment",
    status: "ready",
    imageUrl: "/images/apartamento alto padrao.jpg",
    propertyUrl: "https://ludvigselect.com.br/imovel/apartamento-centro-florianopolis-sc-4-quartos-332m2-36"
  },
  {
    id: "2",
    code: "3197",
    name: "AMC Duo - Empreendimento Multiuso",
    location: "Campinas, São José - SC",
    neighborhood: "Campinas",
    city: "São José",
    price: 450000,
    bedrooms: 1,
    suites: 1,
    area: 50,
    parking: 1,
    description: "Novo ponto de conexão! Torre residencial + comercial + térreo gastronômico. Múltiplas plantas de 50m² a 190m². Sustentabilidade com energia solar, reaproveitamento de água. Ultra conveniente!",
    features: ["Plantas diversas", "Energia solar", "Térreo gastronômico", "Monitoramento facial", "Wi-fi áreas comuns", "Locação estratégica"],
    type: "development",
    status: "launch",
    imageUrl: "/images/Amc Duo.jpg",
    propertyUrl: "https://ludvigselect.com.br/imovel/empreendimento-campinas-sao-jose-sc-3197"
  },
  {
    id: "3",
    code: "123",
    name: "Lançamento Beco Castelo - Campinas - 3Q sendo 2 Suítes",
    location: "Campinas, São José - SC",
    neighborhood: "Campinas",
    city: "São José",
    price: 1350000,
    bedrooms: 3,
    suites: 2,
    area: 114,
    parking: 2,
    description: "No Château Meirelles, sua vida é cercada de praticidade e oferece um estilo de vida moderno, sofisticado e relaxante. Com acabamentos primorosos e um alto padrão construtivo.",
    features: ["Sacada com churrasqueira", "Living 2 ambientes", "Cozinha americana", "2 vagas", "Home box", "Alto padrão"],
    type: "apartment",
    status: "launch",
    imageUrl: "/images/Lancamento beco.jpg",
    propertyUrl: "https://ludvigselect.com.br/imovel/apartamento-campinas-sao-jose-sc-3-quartos-114m2-123"
  },
  {
    id: "4",
    code: "134",
    name: "Reserva Residence - Lançamento AMC",
    location: "Campinas, São José - SC",
    neighborhood: "Campinas",
    city: "São José",
    price: 1200000,
    bedrooms: 3,
    suites: 3,
    area: 121,
    parking: 3,
    description: "Lançamento com todas unidades 3 suítes. Piscina aquecida com hidromassagem, workspace com meeting room. Área de lazer mobiliada e climatizada.",
    features: ["Todas 3 suítes", "Piscina aquecida", "Workspace", "Fechadura eletrônica", "Energia solar"],
    type: "development",
    status: "launch",
    imageUrl: "/images/reserva residence.jpg",
    propertyUrl: "https://ludvigselect.com.br/imovel/empreendimento-campinas-sao-jose-sc-134"
  },
  {
    id: "5",
    code: "3503",
    name: "Apartamento Alto Padrão 130m² - Estreito",
    location: "Estreito, Florianópolis - SC",
    neighborhood: "Estreito",
    city: "Florianópolis",
    price: 1876337,
    bedrooms: 3,
    suites: 3,
    area: 130,
    parking: 2,
    description: "Exclusividade em endereço nobre! 3 suítes espaçosas, lavabo elegante. Poucos passos da Beira-Mar Continental. Infraestrutura completa com áreas de lazer. Ideal para famílias.",
    features: ["3 suítes espaçosas", "Lavabo", "Perto Beira Mar", "Infraestrutura completa", "2 vagas privativas", "Localização nobre"],
    type: "apartment",
    status: "ready",
    imageUrl: "/images/apartamento alto padrao.jpg",
    propertyUrl: "https://ludvigselect.com.br/imovel/apartamento-estreito-florianopolis-sc-3-quartos-130m2-3503"
  },
  {
    id: "6",
    code: "3135",
    name: "Apartamento Pronto para Morar - 20 metros da Beira Mar Norte",
    location: "Agronômica, Florianópolis - SC",
    neighborhood: "Agronômica",
    city: "Florianópolis",
    price: 2300000,
    bedrooms: 2,
    suites: 2,
    area: 108,
    parking: 2,
    description: "20 metros da Beira Mar Norte! Projeto WOA com móveis planejados, sacada com churrasqueira, vista parcial do mar. 26 espaços de lazer em 3.800m² de áreas comuns. Exclusividade total.",
    features: ["20m da Beira Mar", "Vista parcial mar", "Móveis planejados", "26 espaços de lazer", "Projeto WOA", "Churrasqueira", "Design exclusivo"],
    type: "apartment",
    status: "ready",
    imageUrl: "/images/pronto pra morar.jpg",
    propertyUrl: "https://ludvigselect.com.br/imovel/apartamento-agronomica-florianopolis-sc-2-quartos-108m2-3135"
  },
  {
    id: "7",
    code: "3095",
    name: "Apartamento 107m² - 3Q sendo 1 Suíte - Campinas",
    location: "Campinas, São José - SC",
    neighborhood: "Campinas",
    city: "São José",
    price: 1150000,
    bedrooms: 3,
    suites: 1,
    area: 107,
    parking: 2,
    description: "Vista panorâmica livre e definitiva em andar alto. Sacada com churrasqueira, cozinha fechada, varanda íntima exclusiva. Sala estar e jantar integradas. Condomínio com valor atrativo.",
    features: ["Vista panorâmica livre", "Andar alto", "2 salões de festas", "Academia", "Quadra poliesportiva", "Home market", "2 vagas cobertas"],
    type: "apartment",
    status: "ready",
    imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    propertyUrl: "https://ludvigselect.com.br/imovel/apartamento-campinas-sao-jose-sc-3-quartos-107.63m2-3095"
  },
  {
    id: "8",
    code: "132",
    name: "Apartamento 111m² - 3 Suítes + Lavabo - Campinas",
    location: "Campinas, São José - SC",
    neighborhood: "Campinas",
    city: "São José",
    price: 1380000,
    bedrooms: 3,
    suites: 3,
    area: 111,
    parking: 2,
    description: "Apartamento ideal para quem busca conforto e privacidade. Sacada com churrasqueira, lavabo, 3 suítes. Infraestrutura completa com piscina, academia e salão de festas. Localização privilegiada.",
    features: ["3 suítes completas", "Lavabo", "Churrasqueira", "Piscina", "Academia", "Salão de festas", "Localização privilegiada"],
    type: "apartment",
    status: "ready",
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
    propertyUrl: "https://ludvigselect.com.br/imovel/apartamento-campinas-sao-jose-sc-3-quartos-111m2-132"
  },
  {
    id: "9",
    code: "110",
    name: "Apartamento Semi-Mobiliado - Estreito",
    location: "Estreito, Florianópolis - SC",
    neighborhood: "Estreito",
    city: "Florianópolis",
    price: 790000,
    bedrooms: 2,
    suites: 1,
    area: 70,
    parking: 2,
    description: "Apartamento semi-mobiliado com vista parcial para o mar. Cozinha integrada ao living, sacada com churrasqueira, posição solar norte/oeste. Próximo à Beira Mar Continental.",
    features: ["Vista parcial mar", "Semi-mobiliado", "Churrasqueira", "Piscina", "Academia", "Perto Beira Mar", "Vaga dupla"],
    type: "apartment",
    status: "ready",
    imageUrl: "/images/estreito790.jpg",
    propertyUrl: "https://ludvigselect.com.br/imovel/apartamento-estreito-florianopolis-sc-2-quartos-70m2-110"
  },
  {
    id: "10",
    code: "70",
    name: "Apartamento Decorado 135m² - Campinas",
    location: "Campinas, São José - SC",
    neighborhood: "Campinas",
    city: "São José",
    price: 2350000,
    bedrooms: 3,
    suites: 3,
    area: 135,
    parking: 3,
    description: "Pronto para morar! Projeto por arquiteto com móveis planejados, projeto luminotécnico e climatização completa. Com 2 sacadas íntimas, lavabo, living 2 ambientes, churrasqueira.",
    features: ["Totalmente decorado", "Móveis planejados", "Climatização completa", "Piscina térmica", "3 vagas", "Hobby box", "Pronto para morar"],
    type: "apartment",
    status: "ready",
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
    propertyUrl: "https://ludvigselect.com.br/imovel/apartamento-campinas-sao-jose-sc-3-quartos-135m2-70"
  },
  {
    id: "11",
    code: "136",
    name: "Casa de Luxo Jurerê Internacional",
    location: "Jurerê Internacional, Florianópolis - SC",
    neighborhood: "Jurerê Internacional",
    city: "Florianópolis",
    price: 5500000,
    bedrooms: 5,
    suites: 4,
    area: 436,
    parking: 6,
    description: "Casa exclusiva com terreno de 612m². Piscina com hidromassagem e iluminação, 4 suítes mobiliadas com split, closet na master. Energia solar, câmeras, área de lazer gramada com casinha para crianças.",
    features: ["Piscina com hidromassagem", "4 suítes mobiliadas", "Energia solar", "Sistema de segurança", "Área lazer infantil", "6 vagas", "Terreno 612m²"],
    type: "house",
    status: "ready",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    propertyUrl: "https://ludvigselect.com.br/imovel/casa-jurere-internacional-florianopolis-sc-5-quartos-436.64m2-136"
  },
  {
    id: "12",
    code: "121",
    name: "Château Meirelles Art Living",
    location: "Campinas, São José - SC",
    neighborhood: "Campinas",
    city: "São José",
    price: 1100000,
    bedrooms: 3,
    suites: 2,
    area: 91,
    parking: 2,
    description: "Arquitetura refinada e contemporânea. Plantas de 91m² a 175m². Mais de 21 espaços de lazer. Cada detalhe projetado para máxima qualidade de vida. Localização privilegiada próxima de tudo.",
    features: ["21 espaços de lazer", "Arquitetura contemporânea", "2 ou 3 suítes", "Amplitude", "Localização top", "Infraestrutura completa"],
    type: "development",
    status: "launch",
    imageUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80",
    propertyUrl: "https://ludvigselect.com.br/imovel/empreendimento-campinas-sao-jose-sc-121"
  },
  {
    id: "13",
    code: "2501",
    name: "Apartamento 2 Quartos - Campinas",
    location: "Campinas, São José - SC",
    neighborhood: "Campinas",
    city: "São José",
    price: 750000,
    bedrooms: 2,
    suites: 1,
    area: 65,
    parking: 1,
    description: "Apartamento moderno em Campinas com 2 quartos sendo 1 suíte. Cozinha integrada, sacada com churrasqueira. Próximo ao centro comercial e transporte público.",
    features: ["2 quartos", "1 suíte", "Cozinha integrada", "Churrasqueira", "Próximo ao centro", "Transporte público"],
    type: "apartment",
    status: "ready",
    imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    propertyUrl: "https://ludvigselect.com.br/imovel/apartamento-campinas-sao-jose-sc-2-quartos-65m2-2501"
  },
  {
    id: "14",
    code: "2502",
    name: "Apartamento 2 Quartos - Centro",
    location: "Centro, Florianópolis - SC",
    neighborhood: "Centro",
    city: "Florianópolis",
    price: 850000,
    bedrooms: 2,
    suites: 2,
    area: 75,
    parking: 1,
    description: "Apartamento no centro de Florianópolis com 2 suítes. Vista para o mar, cozinha americana, sacada. Localização privilegiada no coração da cidade.",
    features: ["2 suítes", "Vista mar", "Cozinha americana", "Centro da cidade", "Sacada", "Localização privilegiada"],
    type: "apartment",
    status: "ready",
    imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    propertyUrl: "https://ludvigselect.com.br/imovel/apartamento-centro-florianopolis-sc-2-quartos-75m2-2502"
  },
  {
    id: "15",
    code: "2503",
    name: "Apartamento 2 Quartos - Estreito",
    location: "Estreito, Florianópolis - SC",
    neighborhood: "Estreito",
    city: "Florianópolis",
    price: 720000,
    bedrooms: 2,
    suites: 1,
    area: 68,
    parking: 2,
    description: "Apartamento no Estreito com 2 quartos sendo 1 suíte. Vista parcial para o mar, piscina, academia. Próximo à Beira Mar Continental.",
    features: ["2 quartos", "1 suíte", "Vista parcial mar", "Piscina", "Academia", "Perto Beira Mar", "2 vagas"],
    type: "apartment",
    status: "ready",
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
    propertyUrl: "https://ludvigselect.com.br/imovel/apartamento-estreito-florianopolis-sc-2-quartos-68m2-2503"
  }
];